-- THIS FILE IS GENERATED. DO NOT EDIT MANUALLY.
-- stylua: ignore start
return {
  OpenFOAM = { "foam_ls" },
  R = { "r_language_server" },
  V = { "vls" },
  ["assembly-gas"] = { "asm_lsp" },
  ["assembly-go"] = { "asm_lsp" },
  ["assembly-nasm"] = { "asm_lsp" },
  c = { "ccls", "clangd" },
  ["c#"] = { "csharp_ls", "omnisharp" },
  ["c++"] = { "ccls", "clangd" },
  crystal = { "crystalline", "scry" },
  css = { "cssls", "cssmodules_ls" },
  d = { "serve_d" },
  ["f#"] = { "fsautocomplete" },
  fortran = { "fortls" },
  go = { "golangci_lint_ls", "gopls" },
  haskell = { "hls" },
  java = { "jdtls" },
  javascript = { "eslint", "quick_lint_js", "rome", "tsserver" },
  latex = { "ltex", "texlab" },
  liquid = { "theme_check" },
  lua = { "sumneko_lua" },
  markdown = { "marksman", "prosemd_lsp", "remark_ls", "zk" },
  ["metamath-zero"] = { "mm0_ls" },
  nix = { "rnix" },
  ["objective-c"] = { "ccls" },
  onescript = { "bsl_ls" },
  php = { "intelephense", "phpactor", "psalm" },
  python = { "jedi_language_server", "pylsp", "pyright", "sourcery" },
  ruby = { "solargraph", "sorbet" },
  sls = { "salt_ls" },
  solidity = { "solang", "solc", "solidity_ls" },
  sphinx = { "esbonio" },
  sql = { "sqlls", "sqls" },
  swift = { "sourcekit" },
  systemverilog = { "svlangserver", "svls", "verible" },
  terraform = { "terraformls", "tflint" },
  toml = { "taplo" },
  typescript = { "eslint", "rome", "tsserver" },
  verilog = { "verible" },
  vlang = { "vls" },
  vue = { "volar", "vuels" },
  xml = { "lemminx" },
  zig = { "zls" }
}