-- THIS FILE IS GENERATED. DO NOT EDIT MANUALLY.
-- stylua: ignore start
return {
  asyncapi = { "spectral" },
  c = { "ccls", "clangd" },
  ["c#"] = { "csharp_ls", "omnisharp" },
  ["c++"] = { "ccls", "clangd" },
  css = { "cssls", "cssmodules_ls" },
  d = { "serve_d" },
  ["f#"] = { "fsautocomplete" },
  fortran = { "fortls" },
  haskell = { "hls" },
  java = { "jdtls" },
  javascript = { "eslint", "quick_lint_js", "rome", "tsserver" },
  latex = { "ltex", "texlab" },
  lua = { "sumneko_lua" },
  ["objective-c"] = { "ccls" },
  openapi = { "spectral" },
  php = { "intelephense", "phpactor" },
  python = { "jedi_language_server", "pylsp", "pyright" },
  ruby = { "solargraph", "sorbet" },
  solidity = { "solang", "solidity_ls" },
  sphinx = { "esbonio" },
  sql = { "sqlls", "sqls" },
  terraform = { "terraformls", "tflint" },
  typescript = { "eslint", "rome", "tsserver" },
  vue = { "volar", "vuels" },
  xml = { "lemminx" },
  zig = { "zls" }
}